# The routes of the project.
#
# Each route describes how an incoming URL is going
# to be processed by Platform.sh.

# Frontend routes
"https://{default}/":
    type: upstream
    upstream: "frontend:http"
    cache:
      enabled: true

      # Base the cache on the session cookie and custom Drupal cookies. Ignore all other cookies.
      cookies: ['/^SS?ESS/', '/^Drupal.visitor/']

"https://www.{default}/":
    type: redirect
    to: "https://{default}/"

"https://*.dk":
    type: upstream
    upstream: "frontend:http"
    cache:
      enabled: true

      # Base the cache on the session cookie and custom Drupal cookies. Ignore all other cookies.
      cookies: ['/^SS?ESS/', '/^Drupal.visitor/']

# Backend routes
"https://api.*.dk/":
    type: upstream
    upstream: "backend:http"
    cache:
      enabled: true

      # Base the cache on the session cookie and custom Drupal cookies. Ignore all other cookies.
      cookies: ['/^SS?ESS/', '/^Drupal.visitor/']
