# The routes of the project.
#
# Each route describes how an incoming URL is going
# to be processed by Platform.sh.

# Default
"https://api.{default}/":
  type: upstream
  upstream: "backend:http"

# Databrønden
"https://api.os2udoglaer.dk/":
  type: upstream
  upstream: "backend:http"

# Ulfiaarhus
"https://ulfiaarhus.dk/":
  type: upstream
  upstream: "frontend:http"

"https://www.ulfiaarhus.dk/":
  type: upstream
  upstream: "frontend:http"

"https://api.ulfiaarhus.dk/":
  type: upstream
  upstream: "backend:http"

# Mitvadehav
"https://www.mitvadehav.dk/":
  type: upstream
  upstream: "frontend:http"

"https://api.mitvadehav.dk/":
  type: upstream
  upstream: "backend:http"

"https://mitvadehav.dk/":
  type: redirect
  to: "https://www.mitvadehav.dk/"

# Aabenaalborg
"https://aabenaalborg.dk/":
  type: upstream
  upstream: "frontend:http"

"https://api.aabenaalborg.dk/":
  type: upstream
  upstream: "backend:http"

"https://www.aabenaalborg.dk/":
  type: redirect
  to: "https://aabenaalborg.dk/"

# Klcviborg
"https://klcviborg.dk/":
  type: upstream
  upstream: "frontend:http"

"https://api.klcviborg.dk/":
  type: upstream
  upstream: "backend:http"

"https://www.klcviborg.dk/":
  type: redirect
  to: "https://klcviborg.dk/"

# Laeringsportalenskive
"https://laeringsportalenskive.dk/":
  type: redirect
  to: "https://www.laeringsportalenskive.dk/"

"https://www.laeringsportalenskive.dk/":
  type: upstream
  upstream: "frontend:http"

"https://api.laeringsportalenskive.dk/":
  type: upstream
  upstream: "backend:http"

# RUM Thisted
"https://api.rumthisted.dk/":
  type: upstream
  upstream: "backend:http"

"https://www.rumthisted.dk/":
  type: upstream
  upstream: "frontend:http"

"https://rumthisted.dk/":
  type: redirect
  to: "https://www.rumthisted.dk/"

"https://rum.thisted.dk/":
  type: redirect
  to: "https://www.rumthisted.dk/"

"https://www.rum.thisted.dk/":
  type: redirect
  to: "https://www.rumthisted.dk/"

# Udoglaer Randers
"https://udoglaer.randers.dk/":
  type: upstream
  upstream: "frontend:http"

"https://api.udoglaer.randers.dk/":
  type: upstream
  upstream: "backend:http"

# Udoglaer Vejle
"https://udoglaer.vejle.dk/":
  type: upstream
  upstream: "frontend:http"

"https://api.udoglaer.vejle.dk/":
  type: upstream
  upstream: "backend:http"

"https://www.udoglaer.vejle.dk/":
  type: redirect
  to: "https://udoglaer.vejle.dk/"

"https://api-staging.udoglaer.vejle.dk/":
  type: upstream
  upstream: "backend:http"

# Ude NU!
"https://ude.nu/":
  type: upstream
  upstream: "frontend:http"

"https://www.ude.nu/":
  type: upstream
  upstream: "frontend:http"

"https://api.ude.nu":
  type: upstream
  upstream: "backend:http"

# Udsynsmodarbejdsliv
"https://www.udsynmodarbejdsliv.dk/":
  type: upstream
  upstream: "frontend:http"

"https://api.udsynmodarbejdsliv.dk/":
  type: upstream
  upstream: "backend:http"

"https://udsynmodarbejdsliv.dk/":
  type: redirect
  to: "https://www.udsynmodarbejdsliv.dk/"

# Roskilde Kommune
"https://roskilde.os2udoglaer.dk/":
  type: upstream
  upstream: "frontend:http"

"https://api.roskilde.os2udoglaer.dk/":
  type: upstream
  upstream: "backend:http"

"https://www.roskilde.os2udoglaer.dk/":
  type: redirect
  to: "https://roskilde.os2udoglaer.dk/"

